### PR TITLE
Remove reflection for mixins

### PR DESCRIPTION
**Pull request by Alexdoru**
Doing that makes it faster during runtime when rendering the GUI. Also it "adds no extra code" since a bunch of other mods adds the exact same accessors therefore they are all merged as one.

### CODE REVIEW

**Comment by Lyfts** [comment]
Why not use Forge AT's? Those are some of the most commonly AT'd variables

**Comment by Alexdoru** [comment]
idk I don't like forge AT and this mod is most likely going to be used with GT5u which uses modularui and modularui adds the same mixin accessor so it adds no extra code

**Comment by Lyfts** [comment]
ModularUI also adds and uses a bunch of other accessors/invokers for various things in GuiContainer, so they might as well add one for those too. 
To me this just seems like an unnecessary dep & coremod for something that could be boiled down to 4 lines in an AT file.

**Comment by Alexdoru** [comment]
> ModularUI also adds and uses a bunch of other accessors/invokers for various things in GuiContainer, so they might as well add one for those too. To me this just seems like an unnecessary dep & coremod for something that could be boiled down to 4 lines in an AT file. In this instance the AT is as free as it can be since forge will already transform those 4 fields, having mixins & coremod resolved is not nearly as free.

it adds a dep that's already there since this mod is used for GT and GT has mixins, also I don't think it adds much loading time. And I'd rather have that than reflection during runtime in the render loop

**Comment by glowredman** [comment]
I agree with Lyfts. Accessors add a method call which isn't necessary with ATs.

**Pull request closed without merging**
